trigger:
  - main

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Build Job'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '5.x'
              installationPath: $(Agent.ToolsDirectory)/dotnet
          - script: dotnet build
            displayName: 'Build Project'

  - stage: Test
    displayName: 'Test Stage'
    dependsOn: Build
    jobs:
      - job: TestJob
        displayName: 'Test Job'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: dotnet test
            displayName: 'Run Tests'

  - stage: Deploy
    displayName: 'Deploy Stage'
    dependsOn: Test
    jobs:
      - job: DeployJob
        displayName: 'Deploy Job'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: echo "Deploying application..."
            displayName: 'Deploy Application'